language: node_js
node_js:
  - "0.10"
env:
  - DIR=s3fs
  - DIR=webdavfs
before_install: npm install -g grunt-cli bower && bower install
install: sh -c 'cd $DIR' && make install
script: sh -c 'cd $DIR' && make test
notifications:
  email: false
