language: node_js
node_js:
  - "0.10"
env:
  - DIR=s3fs
  - DIR=webdavfs
before_install:
  - npm install -g grunt-cli bower
  - bower install
  - cd testserver
  - npm install
  - make start &
  - cd ..
  - sleep 5
install:
  - cd $DIR
  - make install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - make test
